// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: data.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{0}
}

func (x *Data) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Data) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Grid_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tiles         []*Tile_Data           `protobuf:"bytes,1,rep,name=tiles,proto3" json:"tiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grid_Data) Reset() {
	*x = Grid_Data{}
	mi := &file_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grid_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grid_Data) ProtoMessage() {}

func (x *Grid_Data) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grid_Data.ProtoReflect.Descriptor instead.
func (*Grid_Data) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{1}
}

func (x *Grid_Data) GetTiles() []*Tile_Data {
	if x != nil {
		return x.Tiles
	}
	return nil
}

type Tile_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             float64                `protobuf:"fixed64,1,opt,name=r,proto3" json:"r,omitempty"`
	G             float64                `protobuf:"fixed64,2,opt,name=g,proto3" json:"g,omitempty"`
	B             float64                `protobuf:"fixed64,3,opt,name=b,proto3" json:"b,omitempty"`
	X             int32                  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tile_Data) Reset() {
	*x = Tile_Data{}
	mi := &file_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tile_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile_Data) ProtoMessage() {}

func (x *Tile_Data) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile_Data.ProtoReflect.Descriptor instead.
func (*Tile_Data) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{2}
}

func (x *Tile_Data) GetR() float64 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *Tile_Data) GetG() float64 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *Tile_Data) GetB() float64 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *Tile_Data) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Tile_Data) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Request_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request_Data) Reset() {
	*x = Request_Data{}
	mi := &file_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request_Data) ProtoMessage() {}

func (x *Request_Data) ProtoReflect() protoreflect.Message {
	mi := &file_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request_Data.ProtoReflect.Descriptor instead.
func (*Request_Data) Descriptor() ([]byte, []int) {
	return file_data_proto_rawDescGZIP(), []int{3}
}

func (x *Request_Data) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

var File_data_proto protoreflect.FileDescriptor

const file_data_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"data.proto\x12\x04data\":\n" +
	"\x04Data\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"2\n" +
	"\tGrid_Data\x12%\n" +
	"\x05tiles\x18\x01 \x03(\v2\x0f.data.Tile_DataR\x05tiles\"Q\n" +
	"\tTile_Data\x12\f\n" +
	"\x01r\x18\x01 \x01(\x01R\x01r\x12\f\n" +
	"\x01g\x18\x02 \x01(\x01R\x01g\x12\f\n" +
	"\x01b\x18\x03 \x01(\x01R\x01b\x12\f\n" +
	"\x01x\x18\x04 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x05R\x01y\"\"\n" +
	"\fRequest_Data\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04typeB\aZ\x05/datab\x06proto3"

var (
	file_data_proto_rawDescOnce sync.Once
	file_data_proto_rawDescData []byte
)

func file_data_proto_rawDescGZIP() []byte {
	file_data_proto_rawDescOnce.Do(func() {
		file_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)))
	})
	return file_data_proto_rawDescData
}

var file_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_data_proto_goTypes = []any{
	(*Data)(nil),         // 0: data.Data
	(*Grid_Data)(nil),    // 1: data.Grid_Data
	(*Tile_Data)(nil),    // 2: data.Tile_Data
	(*Request_Data)(nil), // 3: data.Request_Data
}
var file_data_proto_depIdxs = []int32{
	2, // 0: data.Grid_Data.tiles:type_name -> data.Tile_Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_data_proto_init() }
func file_data_proto_init() {
	if File_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_proto_rawDesc), len(file_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_proto_goTypes,
		DependencyIndexes: file_data_proto_depIdxs,
		MessageInfos:      file_data_proto_msgTypes,
	}.Build()
	File_data_proto = out.File
	file_data_proto_goTypes = nil
	file_data_proto_depIdxs = nil
}
